### ISSUE TITLE
export to onnx

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/pytext#190] opened 2019-01-04 23:07 UTC
## Steps to reproduce

  1. train for example the tiny CNN sentence classifier
  2. try to export the model to onnx :  "$ pytext export onnx < demo/configs/docnn.onnx"
  3. see it of course does nt work, the export format being hard coded to Caffe (IIUC)

## Observed Results
  export to default non onnx format
## Expected Results
  an standard onnx file at least for simple cnn based NN  

## Relevant Code
For instance, add a 3rd param to the pytext export in order to choose the model file format:
```
 pytext export onnx < demo/configs/docnn.onnx
```

**Comment by hikushalhere** [comment] 2019-01-08 19:52
Closing this since the task being #187.  Feel free to reopen if the issue is being closed in error.

**Closed by hikushalhere** 2019-01-08 19:52 UTC
